### ISSUE TITLE
Wallet initial sync/restore never finishes

### ISSUE THREAD

**Issue by eagskunst** [horizontalsystems/bitcoin-kit-android#236]
This happens on Bitcoin Tesnet.

I have created several wallets and also tried to recover some, but the sync process never finishes. It always stops at some random point (0, 36/37, 51, 92). The peers always get disconnected and stop receiving MerkleBlockMessages. Also, I have tried in several devices, internet connections and the demo app. The sync never finishes. This started to happen on monday. 

I'm not sure if it's a Testnet Blockchain problem with the p2p connections or a library problem.

**Comment by abdrasulov** [comment]
Hi @eagskunst. There was an issue with getting merkle blocks mainly on TestNet. We've fixed it recently. Could you please check the latest version of the kit and let us know if the initial sync is working?

**Comment by eagskunst** [comment]
> Hi @eagskunst. There was an issue with getting merkle blocks mainly on TestNet. We've fixed it recently. Could you please check the latest version of the kit and let us know if the initial sync is working?

Now is working fine. Thank you!
