### ISSUE TITLE
HTTP used in BTC Testnet instead of HTTPS

### ISSUE THREAD

**Issue by dnsglk** [horizontalsystems/bitcoin-kit-android#405]
Hi guys,

do you plan to use https? 

https://github.com/horizontalsystems/bitcoin-kit-android/blob/2165450bb117413f95851a7d7479d9d3dc164a2e/bitcoinkit/src/main/kotlin/io/horizontalsystems/bitcoinkit/BitcoinKit.kt#L56

**Comment by omurovch** [comment]
Hi @dnsglk,
For now we are not planning to use https. 
If you have an issue with Android not permitting making cleartext http requests, you can configure it to allow for testnet only. Please see https://developer.android.com/guide/topics/manifest/application-element#usesCleartextTraffic

**Comment by dnsglk** [comment]
I see. My original thoughts are more of the security concern, since http may be easily read on the network, although this is the testnet version. Also, the BCH kit uses https for both mainnet and tesnet.

**Comment by omurovch** [comment]
Hi @dnsglk,
Yes you're right, but for now BTC testnet API should be reached only via http.
Thanks
