### ISSUE TITLE
BCH testnet doesn't work

### ISSUE THREAD

**Issue by dnsglk** [horizontalsystems/bitcoin-kit-android#406]
Hi guys,

the blockdozer's API is not accessbile. As per my observation 1 week for sure. The mainnet URL seems to be alive. https://tbch.blockdozer.com/api/status?q=info gives
> Bitcoin JSON-RPC: Request Error: connect ECONNREFUSED 127.0.0.1:18332

Do you plan to fix this issue? I've been trying to find any available public BCH testnet insights API. And unfortunately, still no luck.

Thanks,
Denys

**Comment by omurovch** [comment]
Hi @dnsglk,

Yes, we are aware of this issue, and planning to add alternative API endpoints.
If you will find any working API please let us know.

Thanks

**Comment by dnsglk** [comment]
Hi, yes, sure, I'll post my findings. Thanks.
