### ISSUE TITLE
Establish Contribution Guidlines for Adding Coins

### ISSUE THREAD

**Issue by HashEngineering** [horizontalsystems/bitcoin-kit-android#456]
Could contribution guidelines be published regarding:
1. Coins that are based on the Bitcoin type blockchains
2. Coins that are based on Etherium (ERC-20)

Regarding bitcoin based blockchains, which criteria would be considered:
1. MarketCap (top 10, top 100, etc)
2. new PoW algorithm (which would require new kotlin / native code)
3. Different hash functions than what Bitcoin uses for transactions, signatures, messages, etc (Decred, Blake, Groestlcoin don't use SHA256D for these)
4. Active development and regularity of hard forks (these will relate to maintainability over time)
5. Segwit

I am one of the developers for Groestlcoin and am interested in Guidelines, but these would be useful for other coin developers.

**Comment by abdrasulov** [comment]
Added the first version of contribution guide https://github.com/horizontalsystems/bitcoin-kit-android/blob/master/CONTRIBUTING.md
