### ISSUE TITLE
Signing a message

### ISSUE THREAD

**Issue by jQrgen** [horizontalsystems/bitcoin-kit-android#488]
Hey ho

I'm trying to use this library to sign a message.

This is my current implementation:

```kotlin
    fun signChallenge(challenge: Challenge): SignedChallenge {
        val challengeByteArray = challenge.value.toByteArray()
        val signature = privateKey.createSignature(challengeByteArray)
  }
```

Using the [bitcore library](https://github.com/bitpay/bitcore-message/blob/master/lib/message.js#L33) to verify the message, this signature seems to be faulty

The current `createSignature` derived from the `HDKey extends ECKey` class seems to currently be using the `createSignature`method directly from ECKey which does not seem to be supporting bitcoin signatures

I'm guessing that the `createSignature` in the current implementation is  missing a `magicHash`. An example of  magicHash is implemented in the bitcore-message javascript library here: https://github.com/bitpay/bitcore-message/blob/master/lib/message.js#L33 

If bitcoin message signing was implemented I would use this library, grateful for any help I can receive here.

**Comment by jQrgen** [comment]
PS: Maybe this codesnippet can be leveraged? https://github.com/pokkst/bitcoincashj/blob/5e52bae93d1ff0bd3f93d551716de428a0845f7b/core/src/main/java/org/bitcoinj/core/ECKey.java#L871

**Comment by abdrasulov** [comment]
Hi @jQrgen,

Thanks for your intereseting in our kit. We'll check it soon and inform about the results

**Comment by tmedetbekov** [comment]
Hey, @jQrgen currently we don't support signing & verifying messages, but I have created an issue, and it will be implemented soon.

**Comment by tmedetbekov** [comment]
https://github.com/horizontalsystems/hd-wallet-kit-android/issues/7

**Comment by jQrgen** [comment]
Thanks!

**Comment by tmedetbekov** [comment]
Added two methods:

- ```signMessage(String message)```: creates a base64-encoded signature string
- ```verifySignature(byte[] contents, byte[] signature)```: verifies a signature for the signed content
