### ISSUE TITLE
Question: using inputs from different BIPs at the same time

### ISSUE THREAD

**Issue by Moliholy** [horizontalsystems/bitcoin-kit-android#515]
Good morning. 

I wanted to ask if this library allows to detect transactions sent to addresses with different BIPs (44, 49 and 84), gather the inputs accordingly and use them in a single bitcoin transaction.

For example, say I have:

- 0.1 BTC in m/44'/0'/0'/0/0
- 0.1 BTC in m/49'/0'/0'/0/0
- 0.1 BTC in m/84'/0'/0'/0/0

I would like to send 0.3 BTC (minus fees) in a single transaction. Would this library allow me to do that?

Furthermore: could I track and receive events of incoming and outgoing transaction for all BIPs at the same time, or am I limited to a single BIP?

**Comment by abdrasulov** [comment]
Hi @Moliholy,

It is limited to a single BIP. You can track transactions for all BIPs by creating 3 instances of BitcoinKit. As for mixing inputs, it is not allowed to do so.

**Comment by Moliholy** [comment]
Alright, thanks a lot for the answer!
