### ISSUE TITLE
Checkpoint caculation

### ISSUE THREAD

**Issue by softskillpro** [horizontalsystems/bitcoin-kit-android#523]
@tmedetbekov @omurovch @rafaelekol  
Hi, Awesome @horizontalsystems team!
I wanna add some altcoins here.
But I wonder how can I define checkpoint files for them.
Could you have a chance to tell me?

**Comment by esengulov** [comment]
Checkpoints are relevant for Bitcoin and alike blockchains, you don't need it for ETH or EOS based tokens.

You forgot to mention @abdrasulov for the Android, he is the chief architect for Android platform ;)

**Comment by softskillpro** [comment]
@abdrasulov 
Hi. How are you.
I want your help for my altcoin.
My altcoin is based on bitcoin 17.0.1.

**Comment by tmedetbekov** [comment]
Hi @softskillpro,

To add checkpoints you need to create and register your network class to this [list](https://github.com/horizontalsystems/bitcoin-kit-android/blob/dc9a94cb8bc77daab01bdba16efeb915a06baef4/tools/src/main/java/io/horizontalsystems/tools/BuildCheckpoints.kt#L22) and run our checkpoint syncer [script](https://github.com/horizontalsystems/bitcoin-kit-android/blob/dc9a94cb8bc77daab01bdba16efeb915a06baef4/tools/src/main/java/io/horizontalsystems/tools/Tools.kt#L9). This script will sync checkpoints from the blockchain network and stores hex of checkpoint block (header, height and hash) in resource file. 

If you want to provide checkpoint block's data manually, you can do it in following steps:

 1: Set block's data [here](https://github.com/horizontalsystems/bitcoin-kit-android/blob/dc9a94cb8bc77daab01bdba16efeb915a06baef4/tools/src/main/java/io/horizontalsystems/tools/Tools.kt#L20)
 2: Run [buildCustomCheckpoint](https://github.com/horizontalsystems/bitcoin-kit-android/blob/dc9a94cb8bc77daab01bdba16efeb915a06baef4/tools/src/main/java/io/horizontalsystems/tools/Tools.kt#L9) script 
 3: Store hex of checkpoint block in resource file: ```.../src/main/resources/NetworkName.checkpoint```

**Comment by softskillpro** [comment]
@tmedetbekov 
Thanks for your help.
