### ISSUE TITLE
Sync failed on TestNet

### ISSUE THREAD

**Issue by Sergey221996** [horizontalsystems/bitcoin-kit-android#551]
In last version i am start getting this error after calling start() function, everything was fine in previous versions.
E/InitialSyncer: Initial Sync Error: FileNotFoundException: https://btc-testnet.horizontalsystems.xyz/api
E/BitcoinCore: not synced java.lang.Exception: FileNotFoundException: https://btc-testnet.horizontalsystems.xyz/api

**Comment by abdrasulov** [comment]
Can you please try to open that URL in your mobile browser?

**Comment by Sergey221996** [comment]
Everything fine when I open this urls

**Comment by Sergey221996** [comment]
@abdrasulov fixed with last changes, thank, you very quickly)))

**Comment by nk-the-crazy** [comment]
Issue resolved by downgrading BCOIN to v1.0.2
