### ISSUE TITLE
BitcoinCash TestNet not syncing

### ISSUE THREAD

**Issue by Sergey221996** [horizontalsystems/bitcoin-kit-android#553]
This is my wallet address, I always get 0 balance. 
https://www.blockchain.com/bch-testnet/address/bchtest:qrfxe3um5yg9n3e7sjqrhdjer93j7zqf055a42gmq7
Stacktrace:
E/InitialSyncer: Initial Sync Error: IOException: https://explorer.api.bitcoin.com/tbch/v1, Unexpected Error:Response{protocol=h2, code=404, message=, url=https://explorer.api.bitcoin.com/tbch/v1/addrs/mzhaWV8KYBtLUGZRzVV93DpywzCHBYmFZJ,msi9hg6SVfdJVzwvnQzne3dXteM414Quvz,mutiLJ7EboAqRuVv2CsB9rtHAazb3Dqjpj,mu6mLbFT2vtEpkcivWyzv6Kqxqe5M2jUfq,msjTJXZsrpYgqejPW9vQ7aBQTrxQVMcmdV,mk6csudmHjSScxD1xQsMTfG159AjhJ8bAD,mn3MBsVbArg8gE3bmCsNq9tTxbkt8Gw6Bn,mpcZYvEu1gCtCyFRmfTNgeF45sxzEnbgJk,muc7xqxsBjkojxzBnH2cAzLf369PH82V82,mus4vWiZKKDNCCuvkmmYFPvyUTrJrfSPG2,mtEz9E8K4X6VS7WY1YfYFpBYMsQah4NCRc,n487nEorGscK5FTGcYhEKeZFvqqn3RLNh6,mxvFcYR1JjHtKHERBpZr5BqzTFfksMsb7r,n4juAC6LRPH29Zgd5ypSea1xiKGebsJu5o,mxy1PEtXWR3GB5RTC7jWDFdupXXXAee1St,mmYKhjUjP4SfdZ7gq1WsxrKQd7y6gHR28n,n24nQJHrf68VbyNSdbwpxxmrJxpTnjJbFu,mfwYvxL3HCcdZApH6ZtLHTDjBe2dwwjEZq,mxD6hu6nyXk7sLgyUVjNjkkRmq9Z8bHsMz,mqpSwci6xipRubnNFJDYnJAEBFXG8MzbNh,n3oscNVVw67XebKuMxWDwe6uX2MxYPxiPW,mmh7jXmXWLPd4cJueBu4Ajb75C8ccMXkJm,n2oiUxvLv61UvK8jEYFgjjwcfP4rxMcgeS,mkrtuziaDsJUnwUSdYcVzKkuouLYFvRm5b,miYaYLUGNcH4JVd9PSTbDLCjBDrKujyHz8,muXh8chU9EPqwyxn7QcEr1RKKW3VMHud3K,mv9JqTeN51jWmiVd7BHKNXmamLkydSMJSu,miipo8oWbPgawnoXjsPLvwrh3PWc1YR1S9,mgpHjfHtLv67Xu4eU7SGwHsohgoekxKaVe,n3P3jRtPYSu7zwRKzBKdvArRNF98vuahCb,mu3iKuFf3ryppPogFo2Mb83tdDk2TyCRcC,n3wikZNa4shFqpeRkmRY2ScRnCDrc76nHi,n22Jd4RTAm4VAMeXrXKc3TvZT93KrYxVrc,miRz8QfrDt18BBCu5hEStcXNqtJWQu71PR,mvkHLbUn8TT6NkpPZQkNXbdPGFvd1iCSyQ,mzTSLUstR6YxNaDtRumLzSVrox2J8XXxKT,mkKraMBcwjBQQZkKXgyriU2YEgw1WsVJ31,mrecv9iXz4CumKhEr7Q9zCiJzHTEppLuEA,msoUPc6TbiAKUmB8SNmnxS763JyVimkQrC,n4kVR41chJaFdUALw8SLnm2onWFnffKFUt/txs?from=0&to=50}
2021-09-20 16:47:28.818 15169-15269/co.sentiment E/Bitcoin cash: NotSynced-Exception

**Comment by Sergey221996** [comment]
@abdrasulov maybe its after update checkpoints? Please, give some feedback))

**Comment by abdrasulov** [comment]
Hi @Sergey221996,

We'll check it soon.

**Comment by abdrasulov** [comment]
Hi @Skrypchenko. There is a script `tools/src/main/java/io/horizontalsystems/tools/Tools.kt`. It is used to generate the checkpoint files.
