### ISSUE TITLE
io.horizontalsystems.bitcoincore.exceptions.AddressFormatException: No converter in chain could process the address

### ISSUE THREAD

**Issue by Serpivskyi** [horizontalsystems/bitcoin-kit-android#559]
I trying to send bitcoinCash in testnet, but have this exeption.
 bitcoinCashKit = BitcoinCashKit(
                        context,
                        phrase,
                        "",
                        walletId,
                        networkTypeCash,
                        syncMode = BitcoinCore.SyncMode.NewWallet(),
                        confirmationsThreshold = 1
                    )
address = bitcoincash:qzu7q80gt2mspsyd8nrstwzcly3vhflxjyltlwl5w3
value = (amount * 100000000).toLong(),
feeRate = FeePriority.Medium.feeRate,
sortType = TransactionDataSortType.Shuffle

**Comment by abdrasulov** [comment]
For testnet the address scheme should be "bchtest" instead of "bitcoincash"
